name: Build, Push, and Deploy to Raspberry Pi

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    environment: staging
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build Docker Image
      run: |
        docker build -t ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name }} .

    - name: Push Docker Image
      run: |
        docker push ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name }}
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - name: Debug Environment Variables
      run: |
        echo "PUBLIC_IP: ${{ secrets.PUBLIC_IP }}"
        echo "PI_USERNAME: ${{ secrets.PI_USERNAME }}"
    - name: Deploy to Raspberry Pi
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PUBLIC_IP }}
        username: ${{ secrets.PI_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          echo "Pulling latest image..."
          podman pull ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name }}
          
          echo "Stopping and removing the old container..."
          podman stop myapp || true
          podman rm myapp || true
          
          echo "Starting the new container..."
          podman run -d --name myapp -p 8080:8080 ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ github.ref_name }}
